# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'rskumar'
tagline:          'Hunting NullpointerException'
description:      ''
url:              'https://rskumar.github.io'
baseurl:          /

author:
  name:           'Ravi Kumar'
  url:            'https://rskumar.github.io'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rskumar/
